### ISSUE TITLE
devtools::github_install fails

### ISSUE THREAD

**Issue by waternumbers** [waternumbers/dynatopGIS#1]
devtools::github_install fails to find the Rcpp wrapper functions but cloning and using devtools::install_all works.

**Comment by waternumbers** [comment]
v0.0.2 works for me on my systems. @octopusann @barryhankin please check on yours by doing

remove.packages("dynatopGIS")
devtools::install_github("waternumbers/dynatopGIS")

then trying, for example sink_fill

**Comment by octopusann** [comment]
Will try tomorrow.

Dr. Ann Kretzschmar
Senior Research Associate Q-NFM

B505 LEC 1

Lancaster Environment Centre
Lancaster University
LA1 4YQ

**Comment by octopusann** [comment]
Run dynatopGIS v2 on Swindale. Looks to have run OK but when I move on to the example in the same vignette using Brompton, its falls over in check_model.


The message is Error in dynatop::check_model(model) : param should be a numeric matrix


If you try to list  model$param it says it doesn't exist.


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________
From: Kretzschmar, Ann
Sent: 01 July 2019 17:18:48
To: waternumbers/dynatopGIS
Subject: RE: [waternumbers/dynatopGIS] devtools::github_install fails (#1)


Will try tomorrow.



Dr. Ann Kretzschmar

Senior Research Associate Q-NFM



B505 LEC 1



Lancaster Environment Centre

Lancaster University

LA1 4YQ

**Comment by waternumbers** [comment]
Do you mean the later part of the example where Swindale is run with the Brompton forcing data or the vignette in the dynatop package?

if the later please raise the issue on the issue tracker for the dynatop package.

Assuming the former if model[[3]] returns what looks like the parameter vector the model was generated using the older erroneous version of dynatopGIS.

Check you have the latest version installed and are using it when the model is generated (compared to say an older git clone on your machine).

**Comment by octopusann** [comment]
The example running Swindale with the Brompton data. I followed your instructions to remove and reinstall. I have cloned from github and called in v2 but only in the top level folder.

How can I tell which versaion I have installed? Don’t follow your last comment – sorry.

Dr. Ann Kretzschmar
Senior Research Associate Q-NFM

B505 LEC 1

Lancaster Environment Centre
Lancaster University
LA1 4YQ

**Comment by waternumbers** [comment]
You have both an installed version and the cloned source code. You could be making the function in the library available by either
```
library(dynatopGIS) - which will used the installed version
```
or 
```
devtools::load_all(<path to source code>)
```
which will make the source code you have cloned available.

The instructions I sent where to update the installed version. They will have no effect if you are using devtools::load_all

To check the install version in R run
```
installed.packages()["dynatopGIS",]
```
the version number should be 0.0.2

Alternatively to tell if you are using a version that correctly generates the model start an R session, load the library into R (which ever method described above) and type ```create_model``` at the R prompt
If you are on the latest version you should see a line
```
       pet_input = "unknown", stringsAsFactors = FALSE), param = c(srz_max_default = 0.05, 

```
If however yours looks like
```
       pet_input = "unknown", stringsAsFactors = FALSE), param <- c(srz_max_default = 0.05, 

```
you are on a older version

**Comment by octopusann** [comment]
1) Installed.packages gives me this


installed.packages()["dynatopGIS",]
                                               Package                                                LibPath
                                          "dynatopGIS" "/home/kretzsch/R/x86_64-redhat-linux-gnu-library/3.6"
                                               Version                                               Priority
                                               "0.0.2"                                                     NA
                                               Depends                                                Imports
                                          "R (>= 3.1)"             "Rcpp, raster, sp, rgeos, rgdal, jsonlite"
                                             LinkingTo                                               Suggests
                                                "Rcpp"                      "knitr, rmarkdown, dynatop, covr"
                                              Enhances                                                License
                                                    NA                                                "GPL-2"
                                       License_is_FOSS                                  License_restricts_use
                                                    NA                                                     NA
                                               OS_type                                                 MD5sum
                                                    NA                                                     NA
                                      NeedsCompilation                                                  Built
                                                 "yes"                                                "3.6.0"
so it seems to be picking up the correct version.


 2) typing create_model lists the code. I can only see two instances of pet_input


## initialise the hillslope
    model <- list(hillslope = data.frame(
                      id = raster::unique(brck[[hillslope_class]]),
                      area = raster::zonal(brck[['land_area']],brck[[hillslope_class]],
                                           'sum',digits=4)[,2],
                      atb_bar = raster::zonal(brck[['atb']],brck[[hillslope_class]],
                                              'mean',digits=4)[,2],
                      precip_input="unknown",
                      pet_input="unknown",
                      srz_max="srz_max_default",
                      srz_0="srz_0_default",
                      ln_t0="ln_t0_default",
                      m="m_default",
                      td="td_default",
                      tex="tex_default"
                  ),
                  channel = data.frame(
                      id = raster::unique(brck[['channel_id']]),
                      area = raster::zonal(brck[['channel_area']],brck[['channel_id']],
                                           'sum',digits=4)[,2],
                      precip_input="unknown",
                      pet_input="unknown"
                  ),


It looks quite differen tto your example. It is followed by


param <- c(srz_max_default=0.05,
                             srz_0_default=0.99,
                             ln_t0_default=19,
                             m_default=0.004,
                             td_default=20,
                             tex_default=100)
                  )


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________

**Comment by waternumbers** [comment]
What ever code you have loaded is an old version

**Comment by octopusann** [comment]
Now I’m really confused!  There is something odd going on. The packages list in Rstudio shows version 2. I’ve detached it by unchecking the box and am attempting reattach using the Library command. The shortcut box shows both dynatop and dynatopGIS. If I run the curser over, I get info about dynatop but nothing for dynatopGIS. It is still telling me this is version 2. Now when I type create_model, a different verion of the code is coming up, the new one I think. I’ll try running it again.

I haven’t knowingly done anything different this time!!!

This time it seems to have worked ……..

Dr. Ann Kretzschmar
Senior Research Associate Q-NFM

B505 LEC 1

Lancaster Environment Centre
Lancaster University
LA1 4YQ

**Comment by waternumbers** [comment]
Great . It is really easy to get confused - if in doubt kill your r session and start again :) i do this multiple times a day....

**Comment by octopusann** [comment]
I've run both Swindale and Kent through dynatopGIS now and all seems to be well - will load into GIS to check later.


You've run your example using the data file Brompton.rda  I need to construct data files for the Kent so I can do a test run but I have to admit to confusion over R data structures and lists and how to put it all together. If I'm understanding my notes correctly, we have the model generated by dynatopGIS and I also need a PET time series (can I get away with zeros just for now?) and gridded rainfall. We used a test period of November 2017 for Decipher so I'll do the same. I have a raster containing the the IDs of 262 stations over the catchment which tell us which gauge to use for which cell. Is that the correct format? (hope that makes sense)


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________
