### ISSUE TITLE
verbose printing in create_model

### ISSUE THREAD

**Issue by waternumbers** [waternumbers/dynatopGIS#15]
Currently output looks like
....
    Iteration  1 :  2690  of  9086  HSUs valid 
    Iteration  1 :  2691  of  9086  HSUs valid 
    Iteration  1 :  2692  of  9086  HSUs valid 
    Iteration  1 :  2693  of  9086  HSUs valid 
    Iteration  1 :  2694  of  9086  HSUs valid 
    Iteration  1 :  2695  of  9086  HSUs valid 
    Iteration  1 :  2696  of  9086  HSUs valid
....
Should output once per iteration

**Comment by octopusann** [comment]
Yep, that looks familiar


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________

**Comment by waternumbers** [comment]
Fixed in merge to create v0.2.0.9000
