### ISSUE TITLE
Using raster precipitation / PET as an input 

### ISSUE THREAD

**Issue by dongelmeister** [waternumbers/dynatopGIS#24]
I'm looking to run the dynatop model using a precipitation and PET raster (~50 km resolution). I use a DEM with a resolution of ~250m. Currently the precipitation and PET input data can be linked to the HRU IDs, but the data will be weighted for the HRUs based on the area covered by each precipitation/PET input estimate. I attempted to create an additional class layer using my precipitation/PET rasters such that I can assign the correct data to each HRU. However, when creating the model, I get the following error: 

Error in data.frame(to = as.integer(names(fd[idx])), from = id, frc = fd[idx]/sum(fd[idx])) : 
  arguments imply differing number of rows: 0, 1

My understanding is that the algorithm cannot find a flow direction for the HRU where the error pops up. 

Is there a way around this and use the precipitation/PET raster as a class such that the data is not averaged for the HRUs?  I'm happy to share my code and input data if required.

**Comment by waternumbers** [comment]
The approach using classifications based on precipitation and PET should work, I've used it in the past. 

Your understanding of the error is correct. I've seen it most often in the past when classifications are "missing" - that is not all the classes are specified for every pixel. Could you check:

1) You can generate a model from your data if the precipitation and pet classes aren't used
2) The rasters of precipitation and pet classification have the same extent, resolution and projection as the dem.tif stored by dynatopGIS (presumably they have if you have if you have used the add_layer method)
3) The rasters of precipitation and pet classification are NA where the dem.tif is NA (masked) and have no NA values where the dem.tif is not NA

If you are happy that all of these are the case (or you get problems with (1)) then feel free to put your scripts and data were I can get them (ideally attached to this issue) and I'll take a look

**Comment by waternumbers** [comment]
For future reference this has changed with v0.3 of dynatopGIS. The recommended method is covered in the [training course](https://waternumbers.github.io/dynatop_training/) in the section on [preparing observed series](https://waternumbers.github.io/dynatop_training/11_observed_series.html)
