### ISSUE TITLE
"Adding Catchment Data" - dem file to ctch object

### ISSUE THREAD

**Issue by littlemando** [waternumbers/dynatopGIS#40]
In the vignette, **Building a Dynamic TOPMODEL**, from the dynatopGIS package, I receive an error after running the example code for adding a dem to the ctch object. 

I have the required libraries installed and my version of R is 4.4.1
The following error is: 
![image](https://github.com/user-attachments/assets/a191a5a5-594c-4530-9abb-0bc95944f826)

I had some old code from nearly a year ago that worked fine before, so this is kind of new to me. I checked the NEWS material page for any updates to the function for adding a dem but it doesn't seem like there were any changes. Any help would be appreciated!

**Comment by littlemando** [comment]
Nevermind! After skimming through the vignette ([dynatopGIS](https://github.com/waternumbers/dynatopGIS/tree/master)/[vignettes](https://github.com/waternumbers/dynatopGIS/tree/master/vignettes)
/dynatopGIS.Rmd) I found example code that works. I guess it just hasn't been added to https://cloud.r-project.org/web/packages/dynatopGIS/vignettes/dynatopGIS.html yet. Perhaps I missed this change somewhere.

**Comment by waternumbers** [comment]
@littlemando sorry the version on CRAN (v0.2.\*) is lagging behind the latest on github or r-universe (v0.3.*). If you are running v0.3.\* then the best place to look for documentation is either the vignettes (as you found) or [https://waternumbers.github.io/dynatopGIS/](https://waternumbers.github.io/dynatopGIS/)
