### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by octopusann** [waternumbers/dynatopGIS#6]
Unable to download from github using remove.packages then devtools::install_github('...')

 devtools::install_github('waternumbers/dynatopGIS')
Downloading GitHub repo waternumbers/dynatopGIS@master
Error: Failed to install 'dynatopGIS' from GitHub:
  Command not found
> devtools::install_github('waternumbers/dynatopGIS')
Downloading GitHub repo waternumbers/dynatopGIS@master
Error: Failed to install 'dynatopGIS' from GitHub:
  Command not found

**Comment by octopusann** [comment]
Also cloned and tried load_all

devtools::load_all("C:\\Users\\kretzsch\\Box Sync\\A-QNFM\\DynaTopClones\\dynatopGIS-master_v3\\dynatop-master")
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="C:\Users\kretzsch\Box Sync\A-QNFM\DynaTopClones\dynatopGIS-master_v3\dynatop-master": The system cannot find the file specified

I've tried different locations (BoxSync and S which is our shared drive) and changing \ to / - still no joy

Does BoxSync count as an external location?  Just wonder if that maybe an issue.

**Comment by waternumbers** [comment]
Issue appears stale. Please open a new issue if you still encounter problems.
